spring:
  datasource:
    url: ${SQLSERVER_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  messages:
    basename: messages
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      "[mail.transport.protocol]" : smtp
      "[mail.smtp.auth]" : true
      "[mail.smtp.starttls.enable]" : true
      "[mail.smtp.starttls.required]" : true
      "[mail.debug]" : true
      "[mail.smtp.connectiontimeout]" : 5000
jwt:
  secret:
    key: ${JWT_PRIVATE_KEY}
    expiration:
      in:
        milliseconds: 1200000
