spring:
  datasource:
    url: ${SQLSERVER_URL}
    username: ''
    password: ''
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret:
    key: ${JWT_PRIVATE_KEY}
    expiration:
      in:
        miliseconds: 1200000