application:
  version: 1.0.0
spring:
  application:
    name: security-rest
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
  profiles:
    active: dev
  web:
    resources:
      cache:
        period: 60m
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method